services:
  ai4ef-dashboard:
    image: korbakis/enershare-leif-uc:no-auth
    ports:
      - "3000:3000"
    networks:
      - nginx-proxy-manager_enershare_network
    restart: always
    
  ai4ef-model-app:
    container_name: ai4ef-model-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    command: ["uvicorn", "ai4ef_model_app.api:app", "--host", "0.0.0.0", "--port", "8888"]
    expose:
      - "8888"
    volumes:
      - shared-storage:/leif_app/shared_storage/  # Use a named volume for shared access
      - ./data_mount:/leif_app/data_mount/  # Bind mount for additional folder
    networks:
      - nginx-proxy-manager_enershare_network
    environment:
      - SHARED_STORAGE_PATH=shared_storage/
      - COUNTRY=latvia

  ai4ef-train-app:
    container_name: ai4ef-train-app
    restart: always
    image: ai4ef-train-app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /leif_app/ai4ef_train_app
    command: ["dagster", "dev", "-h", "0.0.0.0", "-p", "8890"]
    expose:
      - "8890"
    volumes:
      - shared-storage:/leif_app/shared_storage/  # Use a named volume for shared access
      - ./data_mount:/leif_app/data_mount/  # Bind mount for additional folder
    ports:
      - "8890:8890"
    networks:
      - nginx-proxy-manager_enershare_network
    environment:
      - SHARED_STORAGE_PATH=shared_storage/
      - API_KEY=APIKEY-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - CONSUMER_AGENT_ID=yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
      - PROVIDER_AGENT_ID=zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz

networks:
  nginx-proxy-manager_enershare_network:
    external: true

volumes:
  shared-storage: # Define the shared volume
