services:
  ai4ef-model-app:
    container_name: ai4ef-model-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${MODEL_APP_PORT}:${MODEL_APP_PORT}"
    command: ["uvicorn", "ai4ef_model_app.api:app", "--host", "0.0.0.0", "--port", "${MODEL_APP_PORT}"]
    expose:
      - "${MODEL_APP_PORT}"
    volumes:
      - ./:/leif_app/code # local dir is translated to leif_app/code in image file system
    networks:
      - nginx-proxy-manager_enershare_network
    environment:
      - SHARED_STORAGE_PATH=shared_storage/
      - COUNTRY=britain

  ai4ef-train-app:
    container_name: ai4ef-train-app
    restart: always
    image: ai4ef-train-app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /leif_app/ai4ef_train_app
    command: ["dagster", "dev", "-h", "0.0.0.0", "-p", "${TRAIN_APP_PORT}"]
    expose:
      - "${TRAIN_APP_PORT}"
    ports:
      - "${TRAIN_APP_PORT}:${TRAIN_APP_PORT}"
    networks:
      - nginx-proxy-manager_enershare_network
    environment:
      - SHARED_STORAGE_PATH=shared_storage/
      - API_KEY=APIKEY-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - CONSUMER_AGENT_ID=urn:ids:enershare:connectors:org:consumer_conn:agent_name
      - PROVIDER_AGENT_ID=urn:ids:enershare:connectors:org:provider_conn:agent_name

networks:
  nginx-proxy-manager_enershare_network:
    external: true
