version: '3'
services:
  leif:
      container_name: leif-service
      restart: always
      image: python:3.10
      ports:
        - "8888:8888"
      build: .
      expose:
        - "8888"
      volumes:
        - ./:/leif_app/code # local dir is translate to leif_app/code in image file system
        # uvicorn api:app --host 0.0.0.0 --port 8888 --reload

  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgresql://read_only_role:read123@enershare.epu.ntua.gr:5556/postgres
      PGRST_DB_SCHEMA: leif
      PGRST_DB_ANON_ROLE: read_only_role #In production this role should not be the same as the one used for the connection
      PGRST_SERVER_PROXY_URI: "http://enershare.epu.ntua.gr:3000"
      PGRST_OPENAPI_SERVER_PROXY_URI: "http://enershare.epu.ntua.gr:3000"
    networks:
      - my_network 

  swagger:
    image: swaggerapi/swagger-ui:latest
    ports:
        - "8080:8080"
    expose:
        - "8080"
    environment:
        API_URL: http://enershare.epu.ntua.gr:3000/      
  
networks:
  my_network:
    driver: bridge
