# This file defines the Kubernetes Ingress resource, which manages HTTP/HTTPS access to the application using the configured hostname and TLS for secure communication. 
apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
  name: {{ .Release.Name }}-{{ .Values.app.service.name }}-ingress 
  annotations: 
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP" 
  labels: 
    release: {{ .Release.Name }} 
 
spec: 
  tls: 
    - hosts: 
        - {{ .Values.app.host }} 
      secretName: "{{ .Release.Name }}-tls" 
  rules: 
    - host: {{ .Values.app.host }} 
      http: 
        paths: 
          - backend: 
              service: 
                name: "{{ .Release.Name }}-{{ .Values.app.service.name }}" 
                port: 
                  number: 80 
            path: / 
            pathType: Prefix 