# This file defines the secret that Kubernetes uses to authenticate and pull the Docker image from Harbor. 
apiVersion: v1 
kind: Secret 
metadata: 
  name: {{ .Release.Name }}-image-pull-secret 
type: kubernetes.io/dockerconfigjson 
data: 
  .dockerconfigjson: {{ template "imagePullSecret" . }} 